
# Stage 1: Build the static assets
FROM node:20.16.0-alpine AS build
WORKDIR /usr/src/nuxt-app

# FIX: Increase Node.js heap memory to avoid OOM during nuxt generate
ENV NODE_OPTIONS="--max-old-space-size=8192 --max-semi-space-size=128"

# Install dependencies
RUN apk update && apk upgrade && apk add git
COPY package*.json ./

ARG NUXT_PUBLIC_ASSET_URL
ARG NUXT_PUBLIC_API_URL
ARG NUXT_PUBLIC_RECAPTCHA
ARG NUXT_PUBLIC_GA_ID
ARG NUXT_PUBLIC_CDN_URL

ENV NUXT_PUBLIC_ASSET_URL=$NUXT_PUBLIC_ASSET_URL
ENV NUXT_PUBLIC_API_URL=$NUXT_PUBLIC_API_URL
ENV NUXT_PUBLIC_RECAPTCHA=$NUXT_PUBLIC_RECAPTCHA
ENV NUXT_PUBLIC_GA_ID=$NUXT_PUBLIC_GA_ID
ENV NUXT_PUBLIC_CDN_URL=$NUXT_PUBLIC_CDN_URL

RUN export

RUN npm install

# Copy the rest of the application files and build the static site
COPY . .
#RUN npm run build
RUN npm run generate

# Stage 2: Serve the static files with Nginx
FROM nginx:alpine AS runtime
COPY --from=build /usr/src/nuxt-app/.output/public /usr/share/nginx/html

# Custom Nginx configuration to serve SPA correctly
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
