sonar.projectKey=sqa_6569be31868e818adaa1bc2d9f02148735561620
sonar.projectName=fe-webcorp
sonar.projectVersion=1.0

sonar.sources=app,assets,components,composables,layouts,pages,plugins,types,utils,public
# sonar.tests=app,assets,components,composables,layouts,pages,plugins,types,utils,public

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.vue.file.suffixes=.vue

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
    node_modules/**,\
    dist/**,\
    build/**,\
    coverage/**,\
    public/**,\
    .idea/**,\
    .vscode/**,\
    .git/**,\
    .env,\
    .env.development,\
    .env.production,\
    *.md,\
    *.txt,\
    *.json,\
    *.lock,\
    *.example,\
    *.bak,\
    *.log,\
    src/main.ts \
    .bridge/** \
    .nuxt/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info


