export interface ParameterSettings {
  "Mengapa UMKM - Title": string;
  "Mengapa UMKM - Description": string;
  "Mengapa UMKM - Image": string;
  "Mengapa UMKM - [1] Percentage": string;
  "Mengapa UMKM - [1] Title": string;
  "Mengapa UMKM - [1] Description": string;
  "Mengapa UMKM - [2] Percentage": string;
  "Mengapa UMKM - [2] Title": string;
  "Mengapa UMKM - [2] Description": string;
  "Mengapa UMKM - [3] Percentage": string;
  "Mengapa UMKM - [3] Title": string;
  "Mengapa UMKM - [3] Description": string;
  "Ekosistem Pendukung - First Line": string;
  "Ekosistem Pendukung - Second Line": string;
  "Ekosistem Pendukung - Image Desktop": string;
  "Ekosistem Pendukung - Image Mobile": string;
  "Kami Adalah Hibank - Title": string;
  "Kami Adalah Hibank - Description": string;
  "Kami Adalah Hibank - Image": string;
  "Visi Hibank - Title": string;
  "Visi Hibank - Description": string;
  "Visi Hibank - Image": string;
  "Visi Hibank - Background Color": string;
  "Mengapa Hibank - Title": string;
  "Mengapa Hibank - Description": string;
  "Mengapa Hibank - [1] Image": string;
  "Mengapa Hibank - [1] Title": string;
  "Mengapa Hibank - [1] Description": string;
  "Mengapa Hibank - [2] Image": string;
  "Mengapa Hibank - [2] Title": string;
  "Mengapa Hibank - [2] Description": string;
  "Mengapa Hibank - [3] Image": string;
  "Mengapa Hibank - [3] Title": string;
  "Mengapa Hibank - [3] Description": string;
  "Mengapa Hibank - Button - Text": string;
  "Mengapa Hibank - Button - Link": string;
  "Mengapa Hibank - Button - Color": string;
  "Layanan Kami - Title": string;
  "Highlights - Title": string;
  "Highlights - Description": string;
  "Highlights - Navigation Link - Title": string;
  "Highlights - Navigation Link - Link": string;
  "Highlights - Navigation Link - Color": string;
  "Kurs - Title": string;
  "Kurs - Exchange Rate - Title": string;
  "Kurs - Calculator - Title": string;
  "Kurs - NAB - Title": string;
  "Kurs - Prime Lending Rate - Title": string;
  "Download App - Title": string;
  "Download App - Description": string;
  "Download App - Navigation Link - Title": string;
  "Download App - Navigation Link - Link": string;
  "Download App - Navigation Link - Color": string;
  "Download App - Play Store Link": string;
  "Download App - Google Play Link": string;
  "Download App - Image": string;
  "Company Group - Title": string;
  "Company Group - Description": string;
  "About Us - Top Section - First Line": string;
  "About Us - Top Section - Second Line": string;
  "About Us - Top Section - Third Line": string;
  "About Us - Top Section - Button Title": string;
  "About Us - Top Section - Button Class Name": string;
  "About Us - Vision - Small Title": string;
  "About Us - Vision - Jumbo Title": string;
  "About Us - Vision - Image": string;
  "About Us - Mission - Title": string;
  "About Us - Mission - Image Desktop": string;
  "About Us - Mission - Image Mobile": string;
  "About Us - Company Values - Title": string;
  "About Us - Company Values - Description": string;
  "About Us - Company Values - Image Desktop": string;
  "About Us - Company Values - Image Mobile": string;
  "About Us - Company History - Title": string;
  "About Us - Company History - Description": string;
  "About Us - Journey - Image Desktop": string;
  "About Us - Journey - Image Mobile": string;
  "About Us - Left Card - Title": string;
  "About Us - Left Card - Description": string;
  "About Us - Left Card - Path": string;
  "About Us - Right Card - Title": string;
  "About Us - Right Card - Description": string;
  "About Us - Right Card - Path": string;
  "About Us - Management - Title": string;
  "About Us - Management - Description": string;
  "About Us - Organization Structure - Image": string;
  "Complaint Form - Dropdown - Topic Type": string;
  "Contact Us Form - Dropdown - Industry Type": string;
  "Contact Us Form - Dropdown - Business Size": string;
  "Contact Us Form - Dropdown - Problem Topic": string;
}
